# Generated by Django 4.0.5 on 2022-06-22 18:39

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('library', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='library.library')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('library', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='library.library')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.PositiveIntegerField(verbose_name='Book ID')),
                ('title', models.CharField(max_length=250, verbose_name='Book Title')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('isbn10', models.CharField(blank=True, max_length=10, null=True, validators=[books.models.isbn_validator], verbose_name='ISBN 10')),
                ('isbn13', models.CharField(blank=True, max_length=13, null=True, validators=[books.models.isbn_validator], verbose_name='ISBN 13')),
                ('lang_code', models.CharField(max_length=15, verbose_name='Language Code')),
                ('publication_date', models.DateField()),
                ('authors_text', models.CharField(editable=False, max_length=250, verbose_name='Authors Name')),
                ('publishers_text', models.CharField(editable=False, max_length=250, verbose_name='Publishers Name')),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Average Rating')),
                ('rating_num', models.PositiveIntegerField(verbose_name='No of Reviews Received')),
                ('instock_qty', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='InStock Qty')),
                ('rented_out_qty', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Rented Out Qty')),
                ('lost_qty', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Lost Qty')),
                ('rent_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Rent Fee')),
                ('book_value', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('pages_in_book', models.PositiveSmallIntegerField(null=True, verbose_name='Pages in Book')),
                ('authors', models.ManyToManyField(to='books.author')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='library.library')),
                ('publishers', models.ManyToManyField(to='books.publisher')),
            ],
        ),
    ]
