# Generated by Django 4.0.5 on 2022-06-22 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Amount')),
                ('duration', models.DurationField(blank=True, editable=False, null=True, verbose_name='Rent Duration')),
                ('is_return', models.BooleanField(default=False, verbose_name='Is Return ?')),
                ('is_lost', models.BooleanField(default=False, verbose_name='Is Lost / Damaged ?')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name='Book Issued on')),
                ('return_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Book Returned on')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='books.book')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to=settings.AUTH_USER_MODEL)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='library.library')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='members.member')),
            ],
            options={
                'get_latest_by': '-created',
            },
        ),
        migrations.CreateModel(
            name='WalletTransacton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_add_balance', models.BooleanField(default=False, verbose_name='Is Add Money Transaction ?')),
                ('balance_before', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, verbose_name='Value before Transaction')),
                ('trans_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Transaction Amount')),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, verbose_name='Value after Transaction')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Transaction Note')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_trans', to=settings.AUTH_USER_MODEL, verbose_name='Librarian')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_trans', to='members.member')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_trans', to='transactions.transaction')),
            ],
            options={
                'get_latest_by': '-created',
            },
        ),
    ]
