# Generated by Django 4.0.5 on 2022-06-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-issue_date']},
        ),
        migrations.AlterModelOptions(
            name='wallettransacton',
            options={'ordering': ['-created']},
        ),
    ]
