# Generated by Django 4.0.5 on 2022-06-23 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='member',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='members.member'),
        ),
    ]
