# Generated by Django 4.0.5 on 2022-06-24 12:56

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_wallet_balance_alter_wallet_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
